name: Scheduled LinkedIn Publisher
on:
  schedule:
    # Runs at 10:00 UTC (11:00 AM Paris Standard Time) every Thursday
    - cron: '0 10 * * 4'
  workflow_dispatch: # Allows to run it manually for testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run posting script
        env:
          NOTION_SECRET: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DB_ID }}
          LINKEDIN_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
          LINKEDIN_URN: ${{ secrets.LINKEDIN_PERSON_URN }}
        run: node publisher.js 
